version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta
        data2: output/sensitivity.dta

  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/phtest.svg  
        figure2: output/phtest_psw.svg
        figure3: output/psgraph.svg 

  multiple_imputation:
    run: stata-mp:latest analysis/multiple_imputation.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/MI.log


  data_preparation_molnupiravir:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_molnupiravir.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_mol.log
      highly_sensitive:
        data: output/main_mol.dta

  cox_regression_molnupiravir:
    run: stata-mp:latest analysis/cox_molnupiravir.do
    needs: [data_preparation_molnupiravir]
    outputs:
      moderately_sensitive:
        log: logs/cox_mol.log
        figure1: output/psgraph_mol.svg 


  generate_study_population_update:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_update
    outputs:
      highly_sensitive:
        cohort: output/input_update.csv

  data_preparation_update:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_update.do
    needs: [generate_study_population_update]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_update.log
      highly_sensitive:
        data: output/main_update.dta
        data2: output/sensitivity_update.dta

  cox_regression_update:
    run: stata-mp:latest analysis/cox_update.do
    needs: [data_preparation_update]
    outputs:
      moderately_sensitive:
        log: logs/cox_update.log
        figure1: output/phtest_update.svg  
        figure2: output/phtest_psw_update.svg
        figure3: output/psgraph_update.svg 

  multiple_imputation_update:
    run: stata-mp:latest analysis/multiple_imputation_update.do
    needs: [data_preparation_update]
    outputs:
      moderately_sensitive:
        log: logs/MI_update.log

  data_preparation_molnupiravir_update:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_molnupiravir_update.do
    needs: [generate_study_population_update]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_mol_update.log
      highly_sensitive:
        data: output/main_mol_update.dta

  cox_regression_molnupiravir_update:
    run: stata-mp:latest analysis/cox_molnupiravir_update.do
    needs: [data_preparation_molnupiravir_update]
    outputs:
      moderately_sensitive:
        log: logs/cox_mol_update.log
        figure1: output/psgraph_mol_update.svg 


  generate_study_population_raw_rate:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_raw_rate
    outputs:
      highly_sensitive:
        cohort: output/input_raw_rate.csv

  data_preparation_raw_rate:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_raw_rate.do
    needs: [generate_study_population_raw_rate]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_raw_rate.log
        table1: output/table.dta
        table2: output/table.csv

  generate_study_population_feasibility:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_feasibility
    outputs:
      highly_sensitive:
        cohort: output/input_feasibility.csv

  data_preparation_feasibility:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_feasibility.do
    needs: [generate_study_population_feasibility]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_feasibility.log

  generate_study_population_feasibility2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_feasibility2
    outputs:
      highly_sensitive:
        cohort: output/input_feasibility2.csv
