version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  data_preparation:
    run: stata-mp:latest analysis/data_preparation_and_descriptives.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta

  cox_regression:
    run: stata-mp:latest analysis/cox.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/cox.log
        figure1: output/phtest.svg  
        figure2: output/phtest_psw.svg

  multiple_imputation:
    run: stata-mp:latest analysis/multiple_imputation.do
    needs: [data_preparation]
    outputs:
      moderately_sensitive:
        log: logs/MI.log


  data_preparation_molnupiravir:
    run: stata-mp:latest analysis/data_preparation_and_descriptives_molnupiravir.do
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        log: logs/data_preparation_mol.log
      highly_sensitive:
        data: output/main_mol.dta

  cox_regression_molnupiravir:
    run: stata-mp:latest analysis/cox_molnupiravir.do
    needs: [data_preparation_molnupiravir]
    outputs:
      moderately_sensitive:
        log: logs/cox_mol.log


  generate_study_population_update:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_update
    outputs:
      highly_sensitive:
        cohort: output/input_update.csv